@startuml
start
:Скачать шаблон проекта;
if (шаблон скачан архивом) then (да)
  : удалить папку googletest в external;
  : подключить связь с googletest репозиторием вручную;
else (нет)
  : инициировать и обновить подмодули;
endif
:Реализовать функцию вычисления **корней** уравнения;
:Написать тесты;
:Выложить в Github;
stop
@enduml